#!/usr/bin/env bash

source ~/.profile
export BASEURL="https://raw.githubusercontent.com/Xiechengqi/scripts/refs/heads/master/install/Agent"

if [ ".${OPENAI_API_BASEURL}" = "." ]
then
read -p "OPENAI_API_BASEURL(eg: https://openrouter.ai/api/v1): " OPENAI_API_BASEURL
[ ".${OPENAI_API_BASEURL}" = "." ] && echo "OPENAI_API_BASEURL can not be empty, exit ..." && exit 1 || echo "export OPENAI_API_BASEURL=\"${OPENAI_API_BASEURL}\"" >> ~/.profile
fi

if [ ".${OPENAI_MODEL}" = "." ]
then
read -p "OPENAI_MODEL(eg: deepseek/deepseek-r1): " OPENAI_MODEL
[ ".${OPENAI_MODEL}" = "." ] && echo "OPENAI_MODEL can not be empty, exit ..." && exit 1 || echo "export OPENAI_MODEL=\"${OPENAI_MODEL}\"" >> ~/.profile
fi

if [ ".${OPENAI_API_KEY}" = "." ]
then
read -p "OPENAI_API_KEY(eg: sk...): " OPENAI_API_KEY
[ ".${OPENAI_API_KEY}" = "." ] && echo "OPENAI_API_KEY can not be empty, exit ..." && exit 1 || echo "export OPENAI_API_KEY=\"${OPENAI_API_KEY}\"" >> ~/.profile
fi

INIT_DATA=$(cat << EOF
{
  "model": "${OPENAI_MODEL}",
  "messages": [
    {"role": "user", "content": "$@"}
  ],
  "tools": [
    {
      "type": "function",
      "function": {
        "name": "get_linux_command_context",
        "description": "获取指定Linux命令运行上下文",
        "parameters": {
          "type": "object",
          "properties": {
            "command": {
              "type": "string",
              "description": "Linux命令，例如 ls -alht /root"
            }
          },
          "required": ["command"]
        }
      }
    },
    {
      "type": "function",
      "function": {
        "name": "get_url_context",
        "description": "获取指定URL内容",
        "parameters": {
          "type": "object",
          "properties": {
            "url": {
              "type": "string",
              "description": "URL 链接，例如 https://google.com"
            }
          },
          "required": ["url"]
        }
      }
    },
    {
      "type": "function",
      "function": {
        "name": "get_token_market_data",
        "description": "获取指定加密货币市场行情数据",
        "parameters": {
          "type": "object",
          "properties": {
            "token": {
              "type": "string",
              "description": "加密货币 token，例如 BTCUSDT"
            }
          },
          "required": ["token"]
        }
      }
    }
  ],
  "tool_choice": "auto"
}
EOF
)
curl -SsL ${OPENAI_API_BASEURL}/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer ${OPENAI_API_KEY}" \
  -d "${INIT_DATA}" 2> /dev/null | grep -E -v '^$' > /tmp/llm.log

cat /tmp/llm.log | jq -r '.choices[0].message.content'

rm -f -v /tmp/llm-step.log
for step in $(cat /tmp/llm.log | jq -r '.choices[0].message.tool_calls[].index')
do
rm -f -v /tmp/llm-step-${step}.log
echo "======= Step ${step} =======" >> /tmp/llm-step-${step}.log
cat /tmp/llm.log | jq --arg STEP "${step}" -r '.choices[0].message.tool_calls[$STEP | tonumber]' | jq -r --arg URL "${BASEURL}" '"curl -SsL \($URL)/\(.function.name + ".sh") | bash -s \(.function.arguments | fromjson | to_entries | map("\(.key)=\(.value)") | join(" "))"' 2> /dev/null > /tmp/cmd.sh
export cmd=$(cat /tmp/cmd.sh)
[ ".${cmd}" != "." ] && echo "=> $(cat /tmp/cmd.sh)" && bash /tmp/cmd.sh &>> /tmp/llm-step-${step}.log
cat /tmp/llm-step-${step}.log | grep -E -v '^$' >> /tmp/llm-step.log
cat /tmp/llm-step-${step}.log
done

echo "用户原始提问内容:$1" >> /tmp/llm-step.log

# 总结
CONTENT=$(cat /tmp/llm-step.log | jq -Rs .)

DATA=$(cat << EOF
{
  "model": "${OPENAI_MODEL}",
  "messages": [
  {"role": "user", "content": ${CONTENT}}
  ]
}
EOF
)

curl -SsL ${OPENAI_API_BASEURL}/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer ${OPENAI_API_KEY}" \
  -d "${DATA}" | jq -r .choices[0].message.content
