{
 "title": "Chain-Info",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "chain_id",
    "label": "Chain",
    "query": {
     "query": "label_values(chain_latest_block_height, chain_id)"
    }
   },
   {
    "name": "validator_moniker",
    "label": "Validator",
    "query": {
     "query": "label_values(validator_bonded_status{chain_id=~\"$chain_id\"}, validator_moniker)"
    }
   },
   {
    "name": "fullnode_moniker",
    "label": "Fullnode",
    "query": {
     "query": "label_values(fullnode_latest_block_height{chain_id=~\"$chain_id\"}, fullnode_moniker)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "chain_latest_block_height{chain_id=~\"$chain_id\"}",
     "legendFormat": "{{ chain_id }}"
    },
    {
     "expr": "3600 / (chain_latest_block_height{chain_id=~\"$chain_id\"} - chain_latest_block_height{chain_id=~\"$chain_id\"} offset 1h)"
    },
    {
     "expr": "chain_latest_block_height{chain_id=~\"$chain_id\"} - chain_latest_block_height{chain_id=~\"$chain_id\"} offset 1m"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "chain_slash_window{chain_id=~\"$chain_id\"}",
     "legendFormat": "chain_id"
    },
    {
     "expr": "chain_slash_min_window_percent{chain_id=~\"$chain_id\"}",
     "legendFormat": "chain_id"
    },
    {
     "expr": "chain_slash_jail_times{chain_id=~\"$chain_id\"}",
     "legendFormat": "chain_id"
    },
    {
     "expr": "chain_slash_jail_percent{chain_id=~\"$chain_id\"}",
     "legendFormat": "chain_id"
    },
    {
     "expr": "chain_slash_double_sign_percent{chain_id=~\"$chain_id\"}",
     "legendFormat": "chain_id"
    }
   ]
  },
  { "title": "Validator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Active",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_validators_number{chain_id=~\"$chain_id\"}",
     "legendFormat": "{{ chain_id }}"
    }
   ]
  },
  {
   "title": "【$chain_id】【$validator_moniker】",
   "type": "table",
   "gridPos": { "h": 6, "w": 22, "x": 2, "y": 4 },
   "targets": [
    {
     "expr": "validator_bonded_status{chain_id=~\"$chain_id\",validator_moniker=~\"$validator_moniker\"}",
     "legendFormat": "{{ chain_id }}{{ validator_moniker }}"
    },
    {
     "expr": "validator_bonded_tokens{chain_id=~\"$chain_id\",validator_moniker=~\"$validator_moniker\"}",
     "legendFormat": "{{ chain_id }}{{ validator_moniker }}"
    },
    {
     "expr": "validator_jailed_status{chain_id=~\"$chain_id\",validator_moniker=~\"$validator_moniker\"}",
     "legendFormat": "{{ chain_id }}{{ validator_moniker }}"
    },
    {
     "expr": "validator_tombstoned_status{chain_id=~\"$chain_id\",validator_moniker=~\"$validator_moniker\"}",
     "legendFormat": "{{ chain_id }}{{ validator_moniker }}"
    }
   ]
  },
  {
   "title": "Missed Blocks【$validator_moniker】",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "validator_missed_blocks{chain_id=~\"$chain_id\",validator_moniker=~\"$validator_moniker\"}",
     "legendFormat": "{{ validator_moniker }}"
    }
   ]
  },
  {
   "title": "Commission Rewards【$validator_moniker】",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "validator_commission_rewards{validator_moniker=~\"$validator_moniker\"}",
     "legendFormat": "{{ validator_moniker }}"
    }
   ]
  },
  {
   "title": "Block Rewards【$validator_moniker】",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "validator_outstanding_rewards{validator_moniker=~\"$validator_moniker\"} - validator_commission_rewards{validator_moniker=~\"$validator_moniker\"}",
     "legendFormat": "{{ validator_moniker }}"
    }
   ]
  },
  { "title": "Fullnode", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "$fullnode_moniker",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "fullnode_latest_block_height{fullnode_moniker=~\"$fullnode_moniker\",chain_id=~\"$chain_id\"}"
    },
    {
     "expr": "fullnode_peers_number{fullnode_moniker=~\"$fullnode_moniker\",chain_id=~\"$chain_id\"}"
    },
    {
     "expr": "fullnode_if_validator{fullnode_moniker=~\"$fullnode_moniker\",chain_id=~\"$chain_id\"}"
    },
    {
     "expr": "fullnode_voting_power{fullnode_moniker=~\"$fullnode_moniker\",chain_id=~\"$chain_id\"}"
    }
   ]
  }
 ]
}